#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Way Huang <way.h@outlook.com>
#

# Prezto Install Dir
PREZTO_INSTALL_DIR="/usr/local/share/zprezto"
if [[ "$OSTYPE" != darwin* ]]; then
  PREZTO_INSTALL_DIR="${ZDOTDIR:-$HOME}/.zprezto"
fi

# Source Prezto.
if [[ -s "${PREZTO_INSTALL_DIR}/init.zsh" ]]; then
  source "${PREZTO_INSTALL_DIR}/init.zsh"
fi

# Customize to your needs...
